FROM rasa/rasa_core

MAINTAINER Deepak Naik "deenaik@gmail.com"

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY . .

RUN pip install service-identity configparser sklearn_crfsuite

VOLUME ["/app/model", "/app/config", "/app/project"]

EXPOSE 5005

ENTRYPOINT ["./entrypoint.sh"]

CMD ["start", "-c", "config.yml", "--path", "/app/projects"]