FROM ubuntu:16.04

MAINTANER Deepak Naik "deenaik@gmail.com"

RUN apt-get update -y && \
    apt-get install -y python-pip python-dev

# We copy just the requirements.txt first to leverage Docker cache
COPY ./chat_ui/requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY ./chat_ui/* /app

ENTRYPOINT [ "python" ]

CMD [ "conversation_interface.py" ]
